# Generated by Django 4.1.3 on 2022-11-24 16:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_rename_csv_file_usermapping_file"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usermapping",
            name="file",
        ),
        migrations.AddField(
            model_name="usermapping",
            name="name",
            field=models.CharField(default=django.utils.timezone.now, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="usermapping",
            name="script",
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
